title: Steph's Space
description: Bookmark this to keep an eye on my project updates!
logo: https://64.media.tumblr.com/4f2fbd52f4b2d786294823b1179ff81e/54b3600b6fb4d3bf-2a/s1280x1920/9a513a574561673d7d651f5a84d6f659a33c895f.gif
show_downloads: true
remote_theme: pages-themes/pages-themes/minimal@v0.2.0
